# This is a basic workflow to help you get started with Actions
name: Dataproc
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs: 
     project_id:
       description: 'Export project ID'
       requried: true	   
  # A workflow run is made up of one or more jobs that can run sequentially or in parallel    
jobs:
  # This workflow contains a single job called "build"
  create_cluster:
   runs-on: ubuntu-latest
   steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set Up Google Cloud SDK Export
      uses: google-github-actions/setup-gcloud@v0.3.0
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ env.project_id }}
        export_default_credentials: true

    - name: Create Dataproc cluster
      run: |
        gcloud dataproc clusters create dev-clus \
          --region= "us-central1" \
          --zone= "us-central1-a" \
          --master-machine-type= "n2-standard-2" \
          --master-boot-disk-size= "10 GB" \
          --num-workers= "2" \
          --worker-machine-type= "n2-standard-2" \
          --worker-boot-disk-size= "10 GB" \
          --image-version= "rhel-cloud/rhel-7" \

    - name: Wait for 8 hours
      run: sleep 600

    - name: Delete Dataproc cluster
      run: |
        gcloud dataproc clusters delete <dev-clus> --region=<us-central1> --quiet
