# This is a basic workflow to help you get started with Actions
name: Dataproc
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs: 
     project_id:
       description: 'Export project ID'
       required: true
  # A workflow run is made up of one or more jobs that can run sequentially or in parallel    
jobs:
  # This workflow contains a single job called "build"
  create_cluster:
   runs-on: ubuntu-latest
   steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set Up Google Cloud SDK Export
      uses: google-github-actions/setup-gcloud@v0.3.0
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ env.project_id }}
        export_default_credentials: true

    - name: Create Dataproc cluster
      run: |
        project_name="${{ github.event.inputs.project_id }}"
        gcloud dataproc clusters create dev-clus \
          --project=Kyndryl-UAT \
          --region=us-east4 \
          --num-workers=2 \
          
    - name: Wait for 10 Mintus
      run: sleep 600

    - name: Delete Dataproc cluster
      run: |
        gcloud dataproc clusters delete <dev-clus> --region=<us-central1> --quiet
